# Generated by Django 3.2.8 on 2021-11-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='name',
            field=models.CharField(default='Auction Name', max_length=32),
        ),
    ]
