# Generated by Django 3.2.8 on 2021-11-12 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Prediction',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='auction',
            name='name',
            field=models.CharField(default='Auction Name', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='auction',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='exam_app.auction'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam_app.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default='login', max_length=16),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateField(default='2019-01-01'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_date',
            field=models.DateField(default='2019-01-01'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam_app.user'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(default='cat', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='desc', max_length=256),
        ),
    ]
