# Generated by Django 3.2.8 on 2021-11-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_auto_20211111_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='user',
        ),
    ]
