# Generated by Django 3.2.8 on 2021-11-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
