# Generated by Django 3.2.8 on 2021-11-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_remove_auction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='start_date',
        ),
    ]
