# Generated by Django 3.2.8 on 2021-11-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0005_auto_20211111_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='end_date',
            field=models.DateField(default='2019-01-01'),
        ),
        migrations.AddField(
            model_name='auction',
            name='start_date',
            field=models.DateField(default='2019-01-01'),
        ),
    ]
