# Generated by Django 3.2.8 on 2021-11-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0005_auto_20211112_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='user_login',
        ),
    ]
