# Generated by Django 3.2.8 on 2021-11-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0008_auto_20211113_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_name',
            field=models.TextField(default='cat', max_length=16),
            preserve_default=False,
        ),
    ]
