# Generated by Django 3.2.8 on 2021-11-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0009_auto_20211113_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='name',
        ),
    ]
