# Generated by Django 3.2.8 on 2021-11-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0011_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_login',
            field=models.CharField(max_length=16),
        ),
    ]
