# Generated by Django 3.2.8 on 2021-11-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0012_alter_user_user_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_login',
        ),
    ]
